Vagrant.configure("2") do |config|
  config.vm.box = "fedora/40-cloud-base"
  
    config.vm.provider "libvirt" do |lv|
    lv.memory = "4098"
    lv.cpus = 2
    lv.graphics_type = "spice"
    lv.video_type = "qxl"
    lv.nic_model_type = "virtio"
    lv.disk_bus = "virtio"
    lv.driver = "kvm"
    lv.uri = 'qemu:///system'
  # Add additional disks
    (1..3).each do |i|
      lv.storage :file, :size => '1G', :type => 'qcow2', :name => "extra_disk_#{i}"
    end
  end


  config.vm.synced_folder "..", "/vagrant", type: "rsync"
  config.vm.synced_folder "..", "/root/localgo", type: "rsync"

  # Provision with Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end

